import type { NessieSnapshot } from "@/lib/types";

export const FIXTURE_CUSTOMER_ID = "fixture-customer-maya";

export function nessieFixture(): NessieSnapshot {
  return {
    source: "fixture",
    fetchedAt: new Date().toISOString(),
    warning:
      "No NESSIE_API_KEY is configured, so this snapshot uses a bundled Capital One sandbox fixture. The five-domain shape matches live Nessie responses.",
    customerId: FIXTURE_CUSTOMER_ID,
    domains: {
      customer: "fixture",
      accounts: "fixture",
      bills: "fixture",
      deposits: "fixture",
      purchases: "fixture",
    },
    customer: {
      id: FIXTURE_CUSTOMER_ID,
      firstName: "Maya",
      lastName: "Chen",
      address: "1420 Green Street, Arlington, VA 22202",
    },
    accounts: [
      {
        id: "fixture-checking",
        type: "Checking",
        nickname: "Everyday Checking",
        balance: 1140,
        rewards: 12,
        customerId: FIXTURE_CUSTOMER_ID,
      },
      {
        id: "fixture-savings",
        type: "Savings",
        nickname: "Emergency Savings",
        balance: 380,
        rewards: 0,
        customerId: FIXTURE_CUSTOMER_ID,
      },
    ],
    bills: [
      {
        id: "fixture-bill-rent",
        accountId: "fixture-checking",
        status: "recurring",
        payee: "Oak Court Property Mgmt",
        nickname: "Rent",
        paymentDate: "2026-09-01",
        recurringDate: 1,
        paymentAmount: 1675,
      },
      {
        id: "fixture-bill-metro",
        accountId: "fixture-checking",
        status: "pending",
        payee: "WMATA",
        nickname: "Metro pass",
        paymentDate: "2026-09-13",
        recurringDate: 13,
        paymentAmount: 127,
      },
      {
        id: "fixture-bill-util",
        accountId: "fixture-checking",
        status: "recurring",
        payee: "Dominion Energy",
        nickname: "Utilities",
        paymentDate: "2026-09-16",
        recurringDate: 16,
        paymentAmount: 142,
      },
      {
        id: "fixture-bill-phone",
        accountId: "fixture-checking",
        status: "recurring",
        payee: "Mint Mobile",
        nickname: "Phone",
        paymentDate: "2026-09-19",
        recurringDate: 19,
        paymentAmount: 78,
      },
      {
        id: "fixture-bill-loan",
        accountId: "fixture-checking",
        status: "recurring",
        payee: "MOHELA",
        nickname: "Student loan",
        paymentDate: "2026-09-27",
        recurringDate: 27,
        paymentAmount: 265,
      },
    ],
    deposits: [
      {
        id: "fixture-dep-payroll",
        accountId: "fixture-checking",
        type: "deposit",
        transactionDate: "2026-08-28",
        status: "completed",
        amount: 2900,
        description: "NORTHWIND PAYROLL",
      },
      {
        id: "fixture-dep-payroll-prev",
        accountId: "fixture-checking",
        type: "deposit",
        transactionDate: "2026-08-14",
        status: "completed",
        amount: 2900,
        description: "NORTHWIND PAYROLL",
      },
      {
        id: "fixture-dep-freelance",
        accountId: "fixture-checking",
        type: "p2p",
        transactionDate: "2026-08-22",
        status: "completed",
        amount: 1100,
        description: "STUDIO BIRCH INVOICE",
      },
    ],
    purchases: [
      {
        id: "fixture-pur-1",
        accountId: "fixture-checking",
        merchantId: "fixture-merchant-grocery",
        purchaseDate: "2026-09-08",
        amount: 54.18,
        status: "completed",
        description: "TRADER JOES",
      },
      {
        id: "fixture-pur-2",
        accountId: "fixture-checking",
        merchantId: "fixture-merchant-transit",
        purchaseDate: "2026-09-07",
        amount: 6.5,
        status: "completed",
        description: "WMATA TAP",
      },
      {
        id: "fixture-pur-3",
        accountId: "fixture-checking",
        merchantId: "fixture-merchant-coffee",
        purchaseDate: "2026-09-06",
        amount: 5.75,
        status: "completed",
        description: "COMPASS COFFEE",
      },
      {
        id: "fixture-pur-4",
        accountId: "fixture-checking",
        merchantId: "fixture-merchant-grocery",
        purchaseDate: "2026-09-03",
        amount: 48.9,
        status: "completed",
        description: "GIANT FOOD",
      },
    ],
  };
}
